/* Generated By:JJTree: Do not edit this line. ASTNegExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTNegExpr extends SimpleNode {
  public ASTNegExpr(int id) {
    super(id);
  }

  public ASTNegExpr(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  // PLB
  private boolean m_isNeg = false;
  public void setNeg() { m_isNeg = true; }
  public boolean isNeg() { return m_isNeg; }
}
