/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java */
package analyzer.ast;

public class ASTIdentifier extends SimpleNode {
  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  // PLB
  private String value = null;
  public void setValue(String v) { value = v; }
  public String getValue() { return value; }

  public boolean isTemporary() {
    if(value.length() < 2 || value.charAt(0) != 't')
      return false;

    String number = value.substring(1);
    return number.matches("[0-9]+");
  }
}
